name: Deploy to EC2 with ECR

on:
  push:
    branches:
      - ecr-deploy # Or your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: true # Add this line
          registry-type: private
          skip-logout: false

      - name: Set up Docker Compose v2
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose

      - name: Build and push Docker images
        run: |
          docker-compose build
          docker-compose push

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.REMOTE_DIR }}
            docker-compose down
            docker-compose pull
            docker-compose up -d --force-recreate