name: Deploy to EC2 with ECR

on:
  push:
    branches:
      - ecr-deploy # Or your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: true
          registry-type: private
          skip-logout: false

      - name: Set up Docker Compose v2
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose

      - name: Build and push Docker images
        run: |
          docker-compose build --no-cache
          docker-compose push 786631761627.dkr.ecr.us-west-1.amazonaws.com/lancechat/backend:latest
          docker-compose push 786631761627.dkr.ecr.us-west-1.amazonaws.com/lancechat/frontend:latest

      - name: Sync files to EC2
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: docker-compose.yml, lancechat.conf, nginx.conf
          target: ${{ secrets.REMOTE_DIR }}

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.REMOTE_DIR }}
            set -e
            docker-compose down
            sudo systemctl stop nginx
            docker-compose pull 786631761627.dkr.ecr.us-west-1.amazonaws.com/lancechat/frontend:latest
            docker-compose pull 786631761627.dkr.ecr.us-west-1.amazonaws.com/lancechat/backend:latest
            docker-compose up -d
            sudo systemctl start nginx