name: Deploy to EC2

on:
  push:
    branches:
      - ecr-deploy # Or your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose v2
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose

      - name: Copy project to EC2
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: . # Copy the entire project directory
          target: ${{ secrets.REMOTE_DIR }}

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.REMOTE_DIR }}
            set -e
            docker-compose down
            sudo systemctl stop nginx
            docker-compose up --build -d
            sudo systemctl start nginx