name: Deploy to EC2 with ECR

on:
  push:
    branches:
      - ecr-deploy # name of desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: true
          registry-type: private
          skip-logout: false

      - name: Build and push Docker images
        run: |
          set -e
          docker build \
            --build-arg OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            --build-arg MONGODB_URI=${{ secrets.MONGODB_URI }} \
            --build-arg DATABASE_NAME=${{ secrets.DATABASE_NAME }} \
            -t lancechat/backend ./backend
          docker build \
            --build-arg NEXT_PUBLIC_FIREBASE_API_KEY=${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }} \
            --build-arg NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }} \
            --build-arg NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }} \
            --build-arg NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }} \
            --build-arg NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }} \
            --build-arg NEXT_PUBLIC_FIREBASE_APP_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }} \
            --build-arg NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }} \
            --build-arg NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }} \
          -t lancechat/frontend ./frontend
          docker tag lancechat/backend:latest 786631761627.dkr.ecr.us-west-1.amazonaws.com/lancechat/backend:latest
          docker tag lancechat/frontend:latest 786631761627.dkr.ecr.us-west-1.amazonaws.com/lancechat/frontend:latest
          docker push 786631761627.dkr.ecr.us-west-1.amazonaws.com/lancechat/backend:latest
          docker push 786631761627.dkr.ecr.us-west-1.amazonaws.com/lancechat/frontend:latest

      - name: Copy docker-compose to EC2
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: docker-compose.yml
          target: ${{ secrets.REMOTE_DIR }}

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.REMOTE_DIR }}
            set -e
            docker-compose down
            sudo systemctl stop nginx
            docker pull 786631761627.dkr.ecr.us-west-1.amazonaws.com/lancechat/frontend:latest
            docker pull 786631761627.dkr.ecr.us-west-1.amazonaws.com/lancechat/backend:latest
            docker-compose up -d
            sudo systemctl start nginx